(function(){
'use strict';
const stages=[
 {id:'detox',n:'01',name:'Детокс',tag:'Мягкий старт и новые привычки',color:'#78A77A',rules:['Выберите один из двух вариантов меню','Каши готовьте на воде','К каждому приёму пищи можно добавить до 100 г овощей'],menus:[['Меню — вариант 1','1. Детокс/Меню_питания_на_ступени_Детокс_вариант_1.pdf'],['Меню — вариант 2','1. Детокс/Меню_питания_на_ступени_Детокс вариант_2.pdf']],docs:[['Медитация любви','1. Детокс/Медитация любви.pdf'],['Список комплиментов','1. Детокс/Список комплиментов.pdf']],shopping:['Крупы: гречка, овсянка, перловка, булгур','Белок: грудка птицы, рыба, яйца, творог','Овощи и зелень','Фрукты и ягоды'],prep:['Отварите 2–3 вида круп на воде','Приготовьте птицу или рыбу без соусов','Вымойте овощи и зелень','Соберите наборы на первые 2–3 дня']},
 {id:'express',n:'02',name:'Экспресс',tag:'Простые рационы на каждый день',color:'#E5A96F',rules:['Клетчатка 3 раза в день','Продукты указаны в готовом виде','Приёмы пищи не смешиваются между днями'],menus:[['Ежедневное меню с рецептами','2. Экспресс/Меню_для_ступени_Экспресс_с_ежедневными_рецептами.pdf'],['Быстрое меню','2. Экспресс/Меню_для_ступени_Экспресс_с_минимальным_временем_на_приготовление.pdf'],['Вегетарианское меню','2. Экспресс/Меню_для_вегетерианцев_ступень_Экспресс.pdf']],docs:[],shopping:['Белок: птица, рыба, творог, яйца','Крупы, бобовые, цельнозерновой хлеб','Кефир, ряженка, йогурт','Овощи, фрукты, зелень'],prep:['Сварите крупы и бобовые','Подготовьте порции птицы или рыбы','Разложите перекусы','Подготовьте бутылку воды']},
 {id:'marathon',n:'03',name:'Марафон',tag:'Глубокая работа с режимом и питанием',color:'#C87668',rules:['День аутофагии — не раньше среды','Обычный день: 5 приёмов пищи','Вечерний перекус — до 19:00'],menus:[['Меню ступени «Марафон»','3. Марафон/Меню питания для ступени Марафон.pdf'],['Меню для дней аутофагии','3. Марафон/Меню питания для дней Аутофагии.pdf'],['Вегетарианское меню','3. Марафон/Меню_для_ступени_МАРАФОН_Вегетарианство,_пескатарианство,_лактовегетарианство.pdf']],docs:[],shopping:['Белковые продукты','Крупы, бобовые и хлеб','Молочные продукты, орехи, масла','Овощи, ягоды и фрукты'],prep:['Сверьте неделю с днём аутофагии','Приготовьте белки и крупы','Отмерьте орехи и масла','Запланируйте вечерний перекус']},
 {id:'balance',n:'04',name:'Баланс',tag:'Система, которая остаётся с вами',color:'#7186AD',rules:['Ориентир меню — 2000 ккал','Пять приёмов пищи','Отслеживайте динамику веса'],menus:[['Меню ступени «Баланс»','4. Баланс/Меню питания для ступени Баланс.pdf']],docs:[],shopping:['Белки и молочные продукты','Овощи, фрукты и зелень','Орехи и масла','Клетчатка'],prep:['Составьте план на 5 приёмов пищи','Подготовьте крупы и белок','Разложите орехи и масла','Подготовьте дневник веса']}
];
const common=[['Сборник метаболических рецептов','1. Сборник метаболических рецептов.pdf'],['Водный режим','2. Водный режим.pdf'],['Правила ужина и перекусы','3. Правила_ужина_и_рецепты_поздних_перекусов.pdf'],['Пособие по клетчатке','5. Пособие по клетчатке.pdf'],['Памятка о жирах','Памятка о жирах.pdf'],['Памятка по холестерину','Памятка по холестерину.pdf'],['Как читать этикетки','Как правильно читать этикетки .pdf']];
const defaultTimes={breakfast:'08:00',snack1:'11:00',lunch:'14:00',snack2:'17:00',dinner:'19:00',evening:'21:00'};
let state={view:'home',stage:null,menu:null,step:0,day:1,days:[],checked:[],query:'',favs:read('met-favs',[]),times:{...defaultTimes,...read('met-times',{})},progress:read('met-progress',{})};
const app=document.getElementById('app');
function read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch(e){return f}}
function enc(path){return path.split('/').map(encodeURIComponent).join('/')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function nav(){return `<nav class="bottomnav"><button data-go="home" class="${state.view==='home'?'active':''}"><span>⌂</span>Главная</button><button data-go="library" class="${state.view==='library'?'active':''}"><span>▤</span>Библиотека</button><button data-go="fav" class="${state.view==='fav'?'active':''}"><span>♡</span>Избранное</button></nav>`}
function home(){let timeFields=[['breakfast','Завтрак'],['snack1','Первый перекус'],['lunch','Обед'],['snack2','Второй перекус'],['dinner','Ужин'],['evening','Вечерний перекус']];return `<section class="hero"><div class="eyebrow">Мой метаболизм</div><h1>Двигайтесь<br><em>в своём ритме</em></h1><p>Все ступени, меню, рецепты и памятки — в одном месте.</p></section><section class="content"><div class="section-title"><span>Ваш путь</span><small>4 ступени</small></div><div class="stage-list">${stages.map(s=>`<button class="stage" data-stage="${s.id}"><span class="stage-num" style="background:${s.color}">${s.n}</span><span><b>${s.name}</b><small>${s.tag}</small></span><i>›</i></button>`).join('')}</div><section class="times"><div class="section-title"><span>Время питания</span><small>Ваш режим</small></div><p>Выберите удобное время — оно появится во всех меню.</p><div class="timegrid">${timeFields.map(x=>`<label><span>${x[1]}</span><input type="time" data-time="${x[0]}" value="${state.times[x[0]]}"></label>`).join('')}</div></section><div class="today"><span>✦</span><div><small>Сегодня</small><b>Начните со стакана воды</b></div><button data-water>Готово</button></div><p class="notice">Материалы не заменяют консультацию врача.</p></section>${nav()}`}
function progressKey(menu=state.menu){return state.stage.id+'|'+menu[1]}
function menuProgress(menu){let p=state.progress[progressKey(menu)];return p?`Текущий день: ${p.current||1} · пройдено: ${(p.completed||[]).length}`:'Покупки → заготовки → дни'}
function getProgress(){let key=progressKey();return state.progress[key]||(state.progress[key]={current:1,completed:[]})}
function saveProgress(){localStorage.setItem('met-progress',JSON.stringify(state.progress))}
function saveActive(){localStorage.setItem('met-active',JSON.stringify({stageId:state.stage.id,menuPath:state.menu[1]}))}
function findProgram(saved){if(!saved)return null;let stage=stages.find(s=>s.id===saved.stageId),menu=stage&&stage.menus.find(m=>m[1]===saved.menuPath);return stage&&menu?{stage,menu}:null}
function stagePage(s){return `<header class="detailhead"><button class="back" data-back>‹</button><span>${s.n} ступень</span><h1>${s.name}</h1><p>${s.tag}</p></header><section class="detailbody"><h2>Главное на ступени</h2><ul>${s.rules.map(x=>`<li>✓ ${x}</li>`).join('')}</ul><h2>Материалы ступени</h2>${s.menus.map((m,i)=>`<button class="planpick" data-menu="${i}"><span>Составить план</span><b>${m[0]}</b><small>${menuProgress(m)}</small><i>›</i></button>`).join('')}${s.docs.map(docRow).join('')}</section>`}
function docRow(d){let fav=state.favs.includes(d[1]);return `<div class="doc"><a href="./materials/${enc(d[1])}" target="_blank"><b>▤ ${d[0]}</b><small>PDF · откроется в новом окне</small></a><button data-fav="${esc(d[1])}">${fav?'♥':'♡'}</button></div>`}
function flow(){let s=state.stage,m=state.menu,labels=['Покупки','Заготовки','Меню по дням'];let head=`<header class="flowhead"><button class="back" data-flowback>‹</button><small>${s.name}</small><h1>${m[0]}</h1><div class="steps">${labels.map((x,i)=>`<span class="${i===state.step?'on':i<state.step?'done':''}"><i>${i<state.step?'✓':i+1}</i>${x}</span>`).join('')}</div></header>`;if(state.step===2)return head+dayPage();let items=state.step?s.prep:s.shopping;return head+`<section class="flowbody"><div class="flowintro"><span>${state.step?'◷':'☐'}</span><div><small>Шаг ${state.step+1} из 3</small><h2>${labels[state.step]}</h2><p>${state.step?'Потратьте около часа заранее.':'Отмечайте купленное.'}</p></div></div><div class="checklist">${items.map((x,i)=>`<button data-check="${i}" class="${state.checked.includes(i)?'checked':''}"><i>${state.checked.includes(i)?'✓':''}</i><span>${x}</span></button>`).join('')}</div><button class="primary" data-next>${state.step?'Перейти к меню':'К заготовкам'} ›</button></section>`}
const mealNames=['Вечерний перекус','Завтрак','Перекус','Обед','Ужин','Вода','Цель'];
function cleanBody(s){return s.replace(/^вариант\.?\s*/i,'').replace(/\s+/g,' ').trim()}
function isContinuation(s){return /^(?:\+|\d+[.)]|с маслом|в блендере|сок|сыр|помидор|шампиньоны|дольками|ингредиенты|приготовление)/i.test(s.trim())}
function blocks(text){if(Array.isArray(text))return text;let re=new RegExp(`(${mealNames.join('|')}):?`,'g'),parts=text.split(re),slots=[],current=null,prefix=(parts[0]||'').trim();if(prefix)slots.push({title:'Меню на день',options:[cleanBody(prefix)]});for(let i=1;i<parts.length;i+=2){let title=parts[i],body=(parts[i+1]||'').trim(),cleaned=cleanBody(body);if(current&&isContinuation(body)){current.options[current.options.length-1]+=` ${body}`;continue}if(current&&current.title===title){current.options.push(cleaned)}else{current={title,options:[cleaned]};slots.push(current)}}return slots.filter(s=>s.options.some(Boolean))}
function timeFor(slot,counts){if(slot.title==='Завтрак')return state.times.breakfast;if(slot.title==='Обед')return state.times.lunch;if(slot.title==='Ужин')return state.times.dinner;if(slot.title==='Вечерний перекус')return state.times.evening;if(slot.title==='Перекус'){counts.snack=(counts.snack||0)+1;return counts.snack===1?state.times.snack1:state.times.snack2}return ''}
function dayPage(){if(!state.days.length)return `<div class="loading"><b>Загружаем меню…</b></div>`;let total=state.days.length,bs=blocks(state.days[state.day-1]||''),counts={},mealNo=0,p=getProgress(),done=p.completed.includes(state.day),current=p.current===state.day,schedule=[['Завтрак',state.times.breakfast],['Перекус',state.times.snack1],['Обед',state.times.lunch],['Перекус',state.times.snack2],['Ужин',state.times.dinner]];return `<section class="days"><div class="dayhero"><small>${state.stage.name} · ${state.menu[0]}</small><h2>День ${state.day}</h2><small>Пройдено ${p.completed.length} из ${total} дней</small></div><div class="progressbox"><button data-current class="${current?'active':''}">${current?'● Это мой текущий день':'Сделать текущим днём'}</button><button data-complete class="${done?'done':''}">${done?'✓ День пройден':'Отметить день пройденным'}</button></div><button class="homebutton" data-home>⌂ На главную</button><div class="schedule">${schedule.map(x=>`<span><b>${x[1]}</b>${x[0]}</span>`).join('')}</div>${bs.map(b=>{let special=['Вода','Цель','Важно','Меню на день'].includes(b.title),time=timeFor(b,counts);if(!special)mealNo++;return `<article class="meal ${special?'special':''}"><span>${special?(b.title==='Вода'?'◌':'✦'):mealNo}</span><div><small>${time?`Приём ${mealNo} · ${time}`:b.title==='Вода'?'В течение дня':'Рекомендация'}</small><h3>${b.title}</h3><div class="variants">${b.options.map((o,i)=>`<div class="variant">${b.options.length>1?`<b>Вариант ${i+1}</b>`:''}<p>${esc(o)}</p></div>`).join('')}</div></div></article>`}).join('')}<div class="daynav"><button data-prev ${state.day===1?'disabled':''}>‹ День ${Math.max(1,state.day-1)}</button><span>${state.day} / ${total}</span><button data-daynext>${state.day===total?'Программа пройдена':'День '+(state.day+1)+' ›'}</button></div></section>`}
function library(favsOnly){let docs=[...common,...stages.flatMap(s=>s.docs)],q=state.query.toLowerCase();docs=docs.filter(d=>(!favsOnly||state.favs.includes(d[1]))&&d[0].toLowerCase().includes(q));return `<section class="page"><div class="pagehead"><small>${favsOnly?'Личная подборка':'Все материалы'}</small><h1>${favsOnly?'Избранное':'Библиотека'}</h1></div>${!favsOnly?`<input class="search" data-search placeholder="Найти памятку или рецепт…" value="${esc(state.query)}">`:''}${docs.map(docRow).join('')||'<p>Пока здесь пусто.</p>'}</section>${nav()}`}
function render(){if(state.view==='stage')app.innerHTML=stagePage(state.stage);else if(state.view==='flow')app.innerHTML=flow();else if(state.view==='library')app.innerHTML=library(false);else if(state.view==='fav')app.innerHTML=library(true);else app.innerHTML=home();window.scrollTo(0,0)}
async function loadMenu(){state.days=[];render();try{let r=await fetch('./menu-data/'+enc(state.menu[1])+'.json');if(!r.ok)throw Error();state.days=await r.json();render()}catch(e){app.querySelector('.loading').innerHTML='<div class="menuerror"><b>Меню не загрузилось</b><p>Проверьте интернет и повторите.</p></div>'}}
app.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.go){state.view=b.dataset.go;render()}else if(b.hasAttribute('data-home')){state.view='home';state.stage=null;state.menu=null;state.days=[];render()}else if(b.dataset.stage){state.stage=stages.find(s=>s.id===b.dataset.stage);state.view='stage';render()}else if(b.hasAttribute('data-back')){state.view='home';render()}else if(b.dataset.menu!==undefined){state.menu=state.stage.menus[+b.dataset.menu];state.step=0;state.checked=[];state.day=getProgress().current||1;state.view='flow';render()}else if(b.hasAttribute('data-flowback')){if(state.step){state.step--;state.checked=[]}else state.view='stage';render()}else if(b.dataset.check!==undefined){let i=+b.dataset.check;state.checked=state.checked.includes(i)?state.checked.filter(x=>x!==i):state.checked.concat(i);render()}else if(b.hasAttribute('data-next')){state.step++;state.checked=[];render();if(state.step===2)loadMenu()}else if(b.hasAttribute('data-current')){getProgress().current=state.day;saveProgress();saveActive();render()}else if(b.hasAttribute('data-complete')){let p=getProgress();p.completed=p.completed.includes(state.day)?p.completed.filter(x=>x!==state.day):p.completed.concat(state.day).sort((a,b)=>a-b);saveProgress();render()}else if(b.hasAttribute('data-prev')){state.day=Math.max(1,state.day-1);render()}else if(b.hasAttribute('data-daynext')){if(state.day===state.days.length){state.view='home';state.stage=null;state.menu=null}else state.day++;render()}else if(b.dataset.fav){let f=b.dataset.fav;state.favs=state.favs.includes(f)?state.favs.filter(x=>x!==f):state.favs.concat(f);localStorage.setItem('met-favs',JSON.stringify(state.favs));render()}});
app.addEventListener('input',e=>{if(e.target.matches('[data-search]')){state.query=e.target.value;let pos=e.target.selectionStart;render();let n=app.querySelector('[data-search]');n.focus();n.setSelectionRange(pos,pos)}else if(e.target.matches('[data-time]')){state.times[e.target.dataset.time]=e.target.value;localStorage.setItem('met-times',JSON.stringify(state.times))}});
function start(){let active=findProgram(read('met-active',null));if(!active){let keys=Object.keys(state.progress);for(let i=keys.length-1;i>=0&&!active;i--){let cut=keys[i].indexOf('|');if(cut>0)active=findProgram({stageId:keys[i].slice(0,cut),menuPath:keys[i].slice(cut+1)})}}if(!active){render();return}state.stage=active.stage;state.menu=active.menu;state.step=2;state.day=getProgress().current||1;state.view='flow';saveActive();loadMenu()}
start();
})();
